version: '3.8'

services:
  keydb:
    image: eqalpha/keydb
    volumes:
      - "/meower-data/keydb:/etc/keydb"
    networks:
      - host
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 10s
        order: stop-first

networks:
  host:
    name: host
    external: true
