services:
  us_west:
    image: ghcr.io/meower-media-co/uploads:latest
    hostname: uploads
    volumes:
      - /meower-data/uploads/.env:/app/.env:ro
      - /meower-data/certs/meower-ca.pem:/etc/ssl/certs/meower-ca.pem:ro
    networks:
      - uploads_us_west
      - server_us_west
    deploy:
      replicas: 3
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 10s
        order: stop-first
      placement:
        constraints:
          - node.labels.region == us_west
          - node.labels.uploads == yes
        preferences:
          - spread: node.labels.zone

  us_west_cf:
    image: cloudflare/cloudflared
    command: tunnel run
    env_file: /meower-data/uploads/cf.env
    networks:
      - uploads_us_west
    depends_on:
      - us_west
    deploy:
      replicas: 3
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 10s
        order: stop-first
      placement:
        constraints:
          - node.labels.region == us_west
          - node.labels.uploads == yes
        preferences:
          - spread: node.labels.zone

networks:
  uploads_us_west:
    external: true
  server_us_west:
    external: true
